name: 'Delete branch artifacts'
description: 'Deletes artifacts of all workflow runs on a branch'
branding:
  icon: trash
  color: red
inputs:
  github-token:
    description: Github token
    required: true
  branch:
    description: All workflow artifacts for uns on this branch will be deleted. If not defined, GITHUB_HEAD_REF will be used (only available for PR triggers).
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
